### PR TITLE
chore: update to eliminate inferred steps improving filing of PR

### PR DESCRIPTION
**Pull request by awentzel**
# Description
Update to change the default values for contributing and testing.  We're still protected as the action of submitting adds accountability for testing and that you have read contribution documentation.  However, now the most frequently PR filers no longer have to check these boxes.

## Motivation & context
Removing the need to constantly update these two values on every PR request when it's inferred that this should always be done.

If we have committed 1500 commits, every one of these requires 5-10 extra seconds to read and check these boxes or 125 wasted minutes.  This omits this need and creates new default.

## Issue type checklist

- [x] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

**Comment by nicholasrice** [comment]
I like that these are both an explicit action by the PR issuer. In general it seems a bit presumptive to auto-check these. Do any other OS projects auto-check have similar fields that are auto-checked?

**Comment by janechu** [comment]
These checks are to help first time contributors, I believe auto-checking any of them defeats the purpose.

**Comment by awentzel** [comment]
The checkmark is not the actual acknowledgement.  It's the "creation" of the PR.  It's my assessment that it's the same end result.  Both, no matter how you get there, upon creation are validation that you have read and performed the necessary checks.  Any other @microsoft/fast-dna-collaborators have opinions here.

**Comment by nicholasrice** [comment]
I just created a chore PR where there were no changes to test - I'd have found it odd if that field was pre-populated for something that didn't need testing.

**Comment by awentzel** [comment]
No concensus reached.

**Pull request closed without merging**
