### PR TITLE
chore: sort examples before adding them to menu

### LINKED ISSUE #852: Toggle should be after Text field on documentation site
**Describe the bug**
If the left navigation is intended to be alphabetical order then text field should come before toggle.

**Screenshots**

[
screen shot 2018-09-05 at 1 40 37 pm
](url)

**To Reproduce**
visit https://msft-docs.azurewebsites.net and look at left nav

**Desktop (please complete the following information):**
all browsers and os's

### PR DESCRIPTION
**Pull request by katakonst**
Sort examples prior adding them to menu

fixes #852

### CODE REVIEW

**Comment by chrisdholt** [comment]
Thanks for the PR for this fix!

Since this doesn’t require a version bump to our packages, can you update this from a “fix” to a “chore”?

**Comment by katakonst** [comment]
Updated!

**Comment by chrisdholt** [comment]
@katakonst - looks like you’ll need to **rebase** with our master branch. (Please don’t use the merge button.)

Thanks!

**Comment by katakonst** [comment]
Updated the branch and also the commit message with the "chore" prefix

**Pull request merged**
