### PR TITLE
fix(fast-animation): updates package to remove vulnerability

### PR DESCRIPTION
**Pull request by nalogiudice**
<body>

<footer>
 

For [details on formatting](https://github.com/Microsoft/fast-dna/wiki/pull-request-guidance) pull requests.

### CODE REVIEW

**Comment by awentzel** [comment]
Vulnerabilities should be treated as high priority.  What is required to complete these?

**Comment by chrisdholt** [comment]
@awentzel The tests need to pass for this to go in.

**Comment by chrisdholt** [comment]
@nalogiudice did you manually edit the package-lock file? I would not expect that these would update without an update to the package.json file, which I don't see.

**Comment by nalogiudice** [comment]
Closing - another clean PR is up in its' place

**Pull request closed without merging**
