### PR TITLE
fix(hypertext): update foreground to use design system colors for theming support

### PR DESCRIPTION
**Pull request by eljefe223**
Closes: #690 
 
For [details on formatting](https://github.com/Microsoft/fast-dna/wiki/pull-request-guidance) pull requests.

### CODE REVIEW

**Comment by chrisdholt** [comment]
Can you update the PR merge message to be more specific regarding the fix. If I'm looking at this, theming is support on a hypertext with an href. This seems to broad and not a fix as written.

**Comment by awentzel** [comment]
Instead of repeating “fix” in the title you should specify what update the was made for the user.

**Comment by chrisdholt** [comment]
@nicholasrice In this instance, I think that we want hypertext without an href to inherit from it's parent rather than specifying a design system color. It seems like this is an issue that needs to be reconciled within the tool rather than modifying the component.

**Comment by nicholasrice** [comment]
@chrisdholt good call - yes we do.

I agree, this is a tooling bug - the region that has it's theme changing should get assigned a the new foreground color. We may run into interesting issues here - color is applied to the html/body elements and will have a lower specificity than the element we apply the new color too.

**Comment by awentzel** [comment]
@nicholasrice as a tooling bug what is the impact on this PR and current status.  It's now marked as stale by the system.  How do we move forward on this?

**Comment by chrisdholt** [comment]
@awentzel The primary question we are asking in this case is if components that would traditionally inherit styles should instead include them. It's an interesting use case because I think in the case of color (such as this), we may want to do so, but we wouldn't want to do so in the case of something like font-family. Last week @nicholasrice and I decided to think on it for a bit and come back to it. I think we just need to land/confirm our position going forward of all components including colors instead of inheriting them.

**Pull request merged**
