### PR TITLE
fix: canUsedForcedColors function is not isomorphic

### PR DESCRIPTION
**Pull request by JamesBurnside**
# Description

new canUsedForcedColors is not isomorphic.
update to have canUseDOM check before accessing window variable.

## Motivation & context

this function currently throws exception when running server side.
Issue #2379 

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

**Comment by JamesBurnside** [comment]
@khamudom for review - this is changing your new function

**Comment by JamesBurnside** [comment]
Also (change for a seperate PR), should this function not be canUseForcedColors instead of canUsedForcedColors (i.e. canUse instead of canUsed)?

**Comment by nicholasrice** [comment]
@JamesBurnside - yea, looks like a typo. We can alias and deprecate the incorrect function name

**Comment by nicholasrice** [comment]
@JamesBurnside also I think you need to run prettier

**Comment by JamesBurnside** [comment]
> @JamesBurnside - yea, looks like a typo. We can alias and deprecate the incorrect function name

Not important for us but probably worth cleaning up if someone has time, created a quick issue for it here #2380

**Pull request merged**
