### PR TITLE
fix: better design-system-provider resolution

### LINKED ISSUE #2992: Devise new mechanism for determining what a DesignSystemProvider is
#2991 introduces a change where determining a design-system-provider is done by comparing tag-names.

While this addresses the immediate issue described in the PR, it doesn't address cases where consumers may be using a design-system-provider with a different tag-name. 

This issue tracks a work item to make design-system resolution more extensible.

### PR DESCRIPTION
**Pull request by nicholasrice**
# Description
Adds a mechanism to register a tag-name as a design-system-provider so that design-system-provider resolution is configurable.

Changing the function to use the `DesignSystemProvider` reference caused a circular reference, so I also needed to re-organize the entities. 

closes #2992
## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
I'm worried that if upgrade hasn't happened yet then `instanceof` will fail.

**Comment by nicholasrice** [comment]
Boo you're right - I didn't think of that. Okay I'll revisit

**Comment by nicholasrice** [comment]
@EisenbergEffect Cool refactored based on our offline conversation

**Comment by janechu** [comment]
Might want to change the description since this is still using tag names 😄

**Pull request merged**
