### PR TITLE
chore: add fast-website to the yarn and lerna workspaces

### PR DESCRIPTION
**Pull request by radium-v**
# Description

This PR adds the new `fast-website` and its `devDependencies` to the Yarn and Lerna workspaces.

## Motivation & context
Since we're temporarily using ultra-new additions from within the repo, we want to make sure our node_modules are pointing to the local neighbor instead of downloading the package independently.

## Issue type checklist
- [x] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

**Comment by radium-v** [comment]
I wasn't sure if commits from master should be rebased or done with a merge commit. I can force-push to redo it if a merge is desired over a rebase.

**Comment by EisenbergEffect** [comment]
I think we're going to squash merge these in the end, so it may not matter as much. Anyone have opinions on this? /cc @nicholasrice @chrisdholt

**Comment by janechu** [comment]
I've been maintaining my own feature branches and just rebasing master and force pushing them every once in a while to keep the history clean, then when the feature branch gets merged i temporarily enable a rebase with master to preserve commit history. This gets a little murkier when multiple contributors are on a branch so I'm not necessarily advocating for that here. However we shouldn't have these commits in the PR, it makes reviewing difficult. I do think that preserving commit history would be nice.

**Comment by chrisdholt** [comment]
I agree with Jane's comments here. I think we'll run into trouble if with additional commits here. If we don't care too much about preserving history on the way back to master, we can leave it as is and squash, but I think it's valuable to have folks' commit history maintained.

**Comment by radium-v** [comment]
Thanks @janechu @EisenbergEffect and @chrisdholt for the input. I'll remove the commits from this PR and we can discuss update strategy elsewhere.

**Pull request merged**
