### PR TITLE
feat(fast-element): style registration and associated behaviors

### PR DESCRIPTION
**Pull request by EisenbergEffect**
# Description

This PR adds the ability to register a set of styles under a global key so that it can be looked up and dynamically applied by key later. Additionally, styles can now have `Behavior` instances associated with them, allowing them the ability to add arbitrary behavior to the custom element to support the added styles.

## Motivation & context

For the full context see issue #2849.

The final API is slightly different than the issue. Here's an example:

```TypeScript
const styles = css`
  ...css goes here...
`.withBehaviors(
    behaviorOne,
    behaviorTwo
  )
  .withKey('fast-button:lightweight');
```

In addition to this, the `Controller` that supports `FastElement` had APIs added for dynamically applying styles and behaviors. For example:

```TypeScript
import { ElementStyles, customElement, FastElement } from '@microsoft/fast-element';

@customElement({ ... })
export class FastButton extends FastElement {
  private appearanceStyles: ElementStyles | null = null;

  @attr appearance: string | null = null;
  appearanceChanged() {
    if (this.appearanceStyles !== null) {
      this.$fastController.removeStyles(this.appearanceStyles);
    }

    this.appearanceStyles = ElementStyles.find(`fast-button:${this.appearance}`);

    if (this.appearanceStyles !== null) {
      this.$fastController.addStyles(this.appearanceStyles);
    }
  }
}
```

This PR also fixes a latent bug in the `css` tagged template helper which would occur if composed styles were anywhere but the beginning or end.

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [x] **New feature**: A change that adds functionality.

This is a non-breaking change.

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@nicholasrice I've enabled instances of `Behavior` to be associated with styles. The behavior interfaces looks like this:

```TypeScript
interface Behavior {
  bind(source: unknown): void;
  unbind(): void;
}
```

When associating behaviors with styles, the `source` for the binding will be the custom element itself. This allows these behaviors to act upon the element, leverage the underlying controller, access the shadow dom, etc. They also participate in the lifecycle, with `bind` being called during `connectedCallback` and `unbind` being called in `disconnectedCallback`. `Behavior`s are a fundamental primitive of the templating engine, so this fits together nicely without having to add recipe-specific concepts to the core. My assumption is that we could wrap recipes up inside behavior instances automatically so that they are easy to apply this way.

Let me know if you think this will work.

**Comment by nicholasrice** [comment]
Yea I think that API will work quite nicely - looking great!

**Comment by chris-phelps** [comment]
@EisenbergEffect : I was trying to incorporate fast-card into a new card type and noticed that there is a very small amount of padding being added. Can this be changed as my design requirements require the image to extend all the way to the border end:

image
image

**Comment by chrisdholt** [comment]
@chris-phelps can you create a new issue to track this, I don't think it's directly related to this PR :)

**Pull request merged**
